name = "project"
about = "Project task runner"

[subcommands.lint]
about = "Run the linter"
run = "cargo clippy --all-targets --all-features --color always"

[subcommands.test]
about = "Run project tests"
run = "cargo test --color always"

[subcommands.e2e]
about = "Run E2E test set"
run = 'nix run ".#checks.x86_64-linux.e2e.driver"'
