on: push

env:
  # Fail on warnings.
  RUSTFLAGS: "--deny warnings"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix develop --command cargo test
      - run: nix develop --command cargo clippy --all-targets --all-features
